# Generated by Django 4.0.2 on 2022-02-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0003_rocket_rename_categories_category_delete_rockets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rocket',
            new_name='Items',
        ),
    ]
