# Generated by Django 4.0.2 on 2022-02-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0004_rename_rocket_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
