# Generated by Django 4.0.2 on 2022-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0005_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
